name: Pipeline
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Linter setup"
        run: |
          pip install flake8
          pip install pylint
      - name: "Linter execution"
        run: |
          flake8 main.py
          pylint main.py
  test:
    needs: [ "lint" ]
    name: "Unit test"
    runs-on: ubuntu-latest
    steps:
      - name: "Retriving main.py"
        uses: actions/checkout@v3
      - name: "Retriving test.py from repository"
        uses: actions/checkout@v3
        with:
          repository: jmoyano/ubiquitous-bassoon
          ref: main
          path: ./testing
      - run: |
          mv testing/test.py test.py
          python -m unittest --verbose --failfast
  build:
    needs: [ "test" ]
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Setup main.py"
      - run: python -c "import main; main.main()"
        name: "Excuting"
      - name: "Uploading artifact"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
  deploy: 
    needs: [ "build" ]
    name: "Deploying"
    runs-on: ubuntu-latest
    steps:
      - name: "Downloading artifact"
        uses: actions/download-artifact@v3
        with:
          name: build
      - run : ls
      - name: "Deploying artifact"
        run: curl -v --stderr deploy.log -w "%{http_code}\n" -F password=${{ secrets.USER_PASSWORD }} -F file=@build/index.html -F user=${{ secrets.USER_NAME }} https://cs.uns.edu.ar/~jose.moyano/index.php 
      - name: "Uploading log"
        uses: actions/upload-artifact@v3
        with:
          name: deploy.log
