name: Pipeline
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Linter setup"
        run: |
          pip install flake8
          pip install pylint
      - name: "Linter execution"
        run: |
          ls
          flake8 main.py
          pylint main.py
  test:
    needs: [ "lint" ]
    name: "Unit test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jmoyano/ubiquitous-bassoon
          ref: main
          path: ./unit-test
      - run: |
          ls
          cd /unit-test
          python -m unittest --verbose --failfast
  build:
    needs: [ "test" ]
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder"
  deploy: 
    needs: [ "build" ]
    name: "Deploying"
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder"
